# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttoken', models.CharField(max_length=6)),
                ('logname', models.CharField(max_length=12)),
                ('logphysicalmap', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttoken', models.CharField(max_length=6)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
