# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageLogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('numrequests', models.IntegerField(default=1)),
            ],
        ),
    ]
