# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('cpupercent', models.IntegerField()),
                ('memoryusage', models.IntegerField()),
                ('ioreadusage', models.IntegerField()),
                ('iowriteusage', models.IntegerField()),
            ],
        ),
    ]
